version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: "elasticsearch"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:6.3.1
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
    ports:
    - "5601:5601"
    networks:
    - esnet
    links:
    - "${es_service}"
    restart: always

networks:
  esnet:
    external: true
